//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DMSDBEntities2 : DbContext
    {
        public DMSDBEntities2()
            : base("name=DMSDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblDealer> tblDealers { get; set; }
        public virtual DbSet<tblLogin> tblLogins { get; set; }
        public virtual DbSet<tblMechanic> tblMechanics { get; set; }
        public virtual DbSet<tblRegister> tblRegisters { get; set; }
        public virtual DbSet<tblService> tblServices { get; set; }
        public virtual DbSet<tblVehicle> tblVehicles { get; set; }
    }
}
