//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string ZipCode { get; set; }
        public string MobileNo { get; set; }
        public string HomePhone { get; set; }
        public string EmailId { get; set; }
        public string Note { get; set; }
    
        public virtual tblCustomer tblCustomer1 { get; set; }
        public virtual tblCustomer tblCustomer2 { get; set; }
    }
}
