//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMechanic
    {
        public int Id { get; set; }
        public string MechanicNo { get; set; }
        public string MechanicName { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
    }
}
